"""Generates the differential oracle for the plural stemmer.

The rules of RSLP were published by Viviane Moreira Orengo and Christian Huyck
(SPIRE 2001). We do not transcribe them by hand — a suffix table written from
memory is the cheapest way to ship a stemmer that almost works. Instead the
published table is read out of a reference implementation and frozen into a
fixture the TypeScript suite can check itself against.

The fixture is committed. The suite must not need Python, pip, a download, or
a network at test time; it needs a file. This script is committed beside it so
the file can be regenerated and inspected, and so that whoever doubts a pair
can see exactly what produced it.

    pip install nltk
    python -c "import nltk; nltk.download('rslp')"
    python scripts/rslp-oracle.py

TWO TRANSCRIPTIONS DISAGREE, and this script uses NLTK's. Compared with
`dfalbel/rslp` `inst/steprules.txt`, NLTK's step 1 carries two exceptions the
other does not: `árvores` on the `res` rule and `depois` on the `s` rule. Both
claim to reproduce the 2001 paper. The primary source does not publish the
rules file and the implementation its page points at answers 403, so there is
no arbiter. NLTK's is the superset, and an extra exception can only protect a
word, never destroy a correct stem — so the conservative direction is this one.

The oracle is the algorithm AS PUBLISHED: rules with their accents, applied to
accented input. The package folds accents before stemming, so it cannot use
this table directly; `src/stemmer.ts` carries a folded projection of it and
explains why. This fixture exists to keep that projection honest — every pair
where the two disagree is listed rather than smoothed over.
"""

from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path

from nltk.stem import RSLPStemmer

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "tests" / "fixtures" / "rslp-s-oracle.json"

# Real text, so the pairs are words that occur rather than words we invented.
# The Machado corpus is in the repository; the normative documents are not yet
# (that is the owner's open decision 4), so their paths are read from the
# environment of whoever regenerates, and absent ones are skipped.
CORPORA = [
    REPO / "bench" / "corpus" / "public" / "machado-memorias-posthumas.txt",
    Path.home() / "nihilo-dev" / "lucius-fundamentum" / "corpus-juridico" / "ldb-9394.txt",
    Path.home() / "nihilo-dev" / "lucius-fundamentum" / "corpus-juridico" / "pne-13005.txt",
]

WORD = re.compile(r"[^\W\d_]+", re.UNICODE)


def fold(text: str) -> str:
    """Lower case and drop combining marks — what `foldForIndex` does in TS."""
    lowered = text.lower()
    return "".join(c for c in unicodedata.normalize("NFD", lowered) if not unicodedata.combining(c))


def main() -> None:
    stemmer = RSLPStemmer()
    plural_step = stemmer._model[0]  # noqa: SLF001 — the published table, step 1

    def rslp_s(word: str) -> str:
        """RSLP-S: the plural step alone, with the step's own precondition."""
        if len(word) < 3 or not word.endswith("s"):
            return word
        return stemmer.apply_rule(word, 0)

    vocabulary: set[str] = set()
    used: list[str] = []
    for path in CORPORA:
        if not path.exists():
            continue
        used.append(path.name)
        vocabulary.update(WORD.findall(path.read_text(encoding="utf-8").lower()))

    plurals = sorted(w for w in vocabulary if len(w) >= 3 and w.endswith("s"))

    fixture = {
        "_readme": (
            "Generated by scripts/rslp-oracle.py from the RSLP table as loaded by NLTK. "
            "`accented` is the algorithm as published; `folded` is what our pipeline must "
            "produce, since it folds accents before stemming. Do not edit by hand."
        ),
        "source": "Orengo & Huyck, SPIRE 2001, via nltk.stem.RSLPStemmer step 1",
        "corpora": used,
        "rules": [
            {
                "suffix": rule[0],
                "minStem": rule[1],
                "replacement": rule[2],
                "exceptions": [e for e in rule[3] if e],
            }
            for rule in plural_step
        ],
        # word -> what the published algorithm gives, then folded. The TS side
        # folds first and stems with a folded table; the pairs where the two
        # disagree are the declared cost of that projection.
        "pairs": {w: fold(rslp_s(w)) for w in plurals},
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(fixture, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"{len(plurals)} pairs from {len(used)} corpora -> {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
